import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'uz' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any;
}

const translations = {
  en: {
    nav: {
      about: 'About',
      skills: 'Skills',
      projects: 'Projects',
      vision: 'Vision',
      goals: 'Goals',
      contact: 'Contact',
      connect: 'Connect',
    },
    hero: {
      status: 'Open to Opportunities',
      shohijahon: 'Shohijahon',
      turdaliyev: 'Turdaliyev',
      titles: ['Future CEO', 'Fintech Founder', 'Trading Strategist'],
      tagline: '"Building a halal financial ecosystem and redefining the future of trading through vision, discipline, and innovation."',
      viewJourney: 'View My Journey',
      contactMe: 'Contact Me',
      stats: {
        age: '17 Years Old',
        ageSub: 'Founder Age',
        english: 'B2 English',
        englishSub: 'CEFR Level',
        startup: 'SafiqX',
        startupSub: 'Startup Vision',
      },
      location: 'Uzbekistan',
      tradingStatus: 'Trading · Active',
      scroll: 'Scroll',
    },
    stats: {
      tradingXP: 'Trading XP',
      tradingSub: 'Smart Money Concepts',
      tradingDetail: 'Bank Manipulation · Order Blocks · Multi-TF',
      projectsBuilt: 'Projects Built',
      projectsSub: 'Active Ventures',
      projectsDetail: 'SafiqX · Trading System · Digital Brand',
      englishLevel: 'English Level',
      englishSub: 'CEFR Certified',
      englishDetail: 'Targeting IELTS 7+ for university admission',
      activeFocus: 'Active Focus',
    },
    about: {
      label: 'About Me',
      title: 'The Story Behind the Vision',
      paragraphs: [
        'I am a 17-year-old ambitious entrepreneur focused on building a global, halal-compliant financial ecosystem. My journey started with a deep curiosity about financial markets and evolved into mastering trading strategies, particularly smart money and bank manipulation concepts.',
        'I am not following the traditional path. While others study theory, I focus on real-world skills — trading, startups, and building systems that can scale globally. I study markets before most people wake up, and I build after school ends.',
        'My mission is to build a company that combines brokerage, asset management, and AI-driven analysis into one powerful platform — changing how people interact with money. Not just for profit, but for empowerment.',
      ],
      quote: '"I am not preparing for the future — I am building it."',
      visionTitle: 'Vision',
      visionText: "To build a global halal brokerage and investment ecosystem that competes with the world's top financial institutions.",
      missionTitle: 'Mission',
      missionText: 'Empower individuals with ethical, powerful, and intelligent financial tools that transcend borders.',
      mindsetTitle: 'Mindset',
      mindsetText: 'Discipline. Strategy. Long-term domination. Every decision is calculated, every move is deliberate.',
    },
    skills: {
      label: 'Expertise',
      title: 'Skills & Mastery',
      subtitle: 'Tap any card to expand. Each skill is a deliberate investment in the future.',
      tapToExplore: 'Tap any card to explore details ↑',
      activeFocus: 'Active Focus',
      categories: {
        business: 'Business & Leadership',
        trading: 'Trading & Finance',
        tech: 'Tech & AI',
        comm: 'Communication',
      },
      descriptions: {
        business: 'Building systems that scale. Every startup begins with a vision — I translate vision into executable strategy.',
        trading: 'Institutional-grade market analysis. I study how banks move price, identify manipulation, and enter with precision.',
        tech: 'Leveraging AI as a competitive weapon. Building intelligent workflows to move faster than any team.',
        comm: 'Language is leverage. I communicate with the precision of a professional and the conviction of a founder.',
      },
      details: {
        'Startup Building': 'From concept to MVP — structuring ideas into fundable, scalable ventures.',
        'Strategic Thinking': 'Multi-level planning: short-term execution + long-term market positioning.',
        'Vision Planning': 'Setting clear north stars, milestones, and KPIs for ambitious companies.',
        'Systems Design': 'Understanding how businesses, products, and processes interconnect at scale.',
        'Smart Money Concepts (SMC)': 'Tracking institutional order flow, premium/discount zones, and FVGs.',
        'Liquidity & Order Blocks': 'Identifying where banks place stop hunts and accumulate positions.',
        'Market Structure (BOS, CHoCH)': 'Reading Break of Structure and Change of Character for trend confirmation.',
        'Multi-timeframe Analysis': 'D1 narrative → H4 confirmation → M15 precision entry model.',
        'Bank Manipulation Strategy': 'Personal edge built on understanding how large players engineer liquidity.',
        'Prompt Engineering': 'Crafting precise instructions to extract maximum value from AI models.',
        'AI-powered Workflows': 'Automating research, analysis, and content generation pipelines.',
        'Fullstack Understanding': 'Frontend, backend, database — knowing how every layer connects.',
        'Frontend / Backend / DB': 'Practical knowledge of modern web architecture for startup building.',
        'English — CEFR B2': 'Actively pursuing IELTS 7+ for top international university entry.',
        'Professional Writing': 'Business communication, investor briefs, and strategic documentation.',
        'Presentation Skills': 'Pitching ideas with clarity, confidence, and visual storytelling.',
        'Strategic Storytelling': 'Shaping narratives that attract investors, partners, and top talent.',
      }
    },
    projects: {
      label: 'Projects',
      title: "What I'm Building",
      subtitle: 'Real ventures in development — not school projects.',
      status: {
        dev: 'In Development',
        research: 'Active Research',
        active: 'Active',
      },
      safiqx: {
        tag: 'Startup Concept',
        title: 'SafiqX',
        sub: 'Brokerage & Investment Company',
        desc: 'A next-generation halal brokerage platform combining trading execution, advanced analytics (like TradingView), and AI-driven insights. Inspired by BlackRock-level infrastructure.',
        h1: 'Trading execution engine',
        h2: 'AI-based market insights',
        h3: 'Asset management system',
        h4: 'Halal-compliant structure',
      },
      trading: {
        tag: 'Personal Strategy',
        title: 'Trading System',
        sub: 'Bank Manipulation Strategy',
        desc: 'A personal trading strategy built on Smart Money Concepts — identifying bank order flow, key liquidity zones, and structure shifts across multiple timeframes.',
        h1: 'Smart Money Concepts (SMC)',
        h2: 'Multi-timeframe model (D1→M15)',
        h3: 'Liquidity sweep identification',
        h4: 'Risk-managed structure',
      },
      identity: {
        tag: 'Personal Brand',
        title: 'Digital Identity',
        sub: 'Portfolio & Personal Brand',
        desc: 'Building a high-converting digital identity designed to attract university admissions, investors, and strategic partners. Every touchpoint communicates vision and ambition.',
        h1: 'Investor-grade presentation',
        h2: 'University portfolio targeting',
        h3: 'Strategic personal narrative',
        h4: 'Global visibility system',
      }
    },
    vision: {
      label: 'Future Company',
      title: 'SafiqX — The Vision',
      subtitle: "A next-generation halal brokerage and investment platform built to compete with the world's top financial institutions.",
      quote: '"SafiqX is not just a fintech company. It is a movement — to give every Muslim and ethical investor access to world-class financial infrastructure."',
      mission: 'SafiqX Mission',
      goal: 'Goal: Global leader in ethical finance',
      pillars: {
        p1: 'Trading Execution',
        p1d: 'Institutional-grade execution engine for retail and professional traders worldwide.',
        p2: 'Advanced Analytics',
        p2d: 'TradingView-level charting and market structure analysis powered by real-time data.',
        p3: 'AI-Driven Insights',
        p3d: 'Machine learning models that identify high-probability setups and market patterns.',
        p4: 'Asset Management',
        p4d: 'BlackRock-inspired systematic portfolio management for individual and institutional investors.',
        p5: 'Halal Compliance',
        p5d: 'Fully Shariah-compliant structure ensuring ethical investing for 1.8 billion Muslims globally.',
      }
    },
    goals: {
      label: 'Roadmap',
      title: 'Goals & Milestones',
      subtitle: 'A structured, phased approach to building a global financial empire — starting today.',
      phases: {
        p1: 'Phase I',
        p1t: '2026 — Short-Term',
        p2: 'Phase II',
        p2t: '2027–2028 — Mid-Term',
        p3: 'Phase III',
        p3t: '5–10 Years — Long-Term',
      },
      items: {
        ielts: 'Achieve IELTS 7+',
        portfolio: 'Build strong university portfolio',
        mvp: 'Develop startup MVP (SafiqX)',
        ai: 'Improve prompt engineering & AI skills',
        trading: 'Establish active trading performance record',
        uni: 'Enter top international university',
        beta: 'Launch SafiqX beta platform',
        capital: 'Build strong trading capital base',
        team: 'Form advisory and founding team',
        investor: 'Secure initial investor interest',
        ceo: 'Become CEO of global fintech company',
        ecosystem: 'Build multi-billion halal investment ecosystem',
        global: 'Expand SafiqX to global markets',
        compete: 'Compete with top-tier financial institutions',
        empower: 'Empower millions through ethical finance',
      }
    },
    achievements: {
      label: 'Achievements',
      title: "What I've Earned",
      subtitle: 'Real accomplishments at 17 — foundations of something much larger.',
      more: 'More achievements being added as the journey continues...',
      items: {
        english: 'CEFR B2 English',
        englishSub: 'Language Proficiency',
        englishDesc: 'Achieved B2 level in English, actively working toward IELTS 7+ for top international university admission.',
        trader: 'Active SMC Trader',
        traderSub: 'Trading Mastery',
        traderDesc: 'Mastering Smart Money Concepts — deep understanding of bank manipulation, order blocks, and market structure.',
        safiqx: 'SafiqX Concept Founded',
        safiqxSub: 'Startup Development',
        safiqxDesc: 'Created the full concept, vision, and infrastructure blueprint for a halal fintech brokerage platform.',
        ai: 'AI & Prompt Engineering',
        aiSub: 'Tech Skills',
        aiDesc: 'Self-taught proficiency in AI tools, workflow automation, and prompt engineering for business applications.',
      }
    },
    contact: {
      label: 'Contact',
      title: "Let's Connect",
      subtitle: "Reach out directly via any channel — or send a message below and I'll get back to you.",
      email: 'Email',
      telegram: 'Telegram',
      linkedin: 'LinkedIn',
      tapTo: 'Tap to',
      open: 'Open',
      sendMsg: 'Send a Message',
      form: {
        name: 'Name',
        email: 'Email',
        subject: 'Subject',
        message: 'Message',
        namePlaceholder: 'Your name',
        emailPlaceholder: 'your@email.com',
        subjectPlaceholder: "What's this about?",
        messagePlaceholder: 'Tell me about your idea, opportunity, or question...',
        send: 'Send Message',
        sending: 'Sending...',
        success: 'Message Sent!',
        successSub: "Thanks! I'll get back to you as soon as possible.",
        sendAnother: 'Send Another',
        error: 'Something went wrong. Please try emailing directly.',
        required: 'Please fill in all required fields.',
      },
      quote: '"I am not preparing for the future — I am building it."',
      response: 'Typically responds within 24h',
      responseSub: 'All messages saved · Check Telegram for faster replies',
      emailMe: 'Email Me Directly',
      msgTelegram: 'Message on Telegram',
    },
    footer: {
      sub: 'Future CEO · Fintech Founder · Uzbekistan · 2026',
      built: 'Built with vision.',
    }
  },
  uz: {
    nav: {
      about: 'Haqimda',
      skills: 'Ko\'nikmalar',
      projects: 'Loyihalar',
      vision: 'Niyatlar',
      goals: 'Maqsadlar',
      contact: 'Aloqa',
      connect: 'Bog\'lanish',
    },
    hero: {
      status: 'Imkoniyatlar uchun ochiq',
      shohijahon: 'Shohijahon',
      turdaliyev: 'Turdaliyev',
      titles: ['Kelajakdagi CEO', 'Fintex Asoschisi', 'Trading Strategi'],
      tagline: '"Halol moliyaviy ekotizim yaratish va trading kelajagini bilim, intizom va innovatsiyalar orqali qayta shakllantirish."',
      viewJourney: 'Yo\'limni ko\'rish',
      contactMe: 'Men bilan bog\'lanish',
      stats: {
        age: '17 Yoshda',
        ageSub: 'Asoschi yoshi',
        english: 'B2 Ingliz tili',
        englishSub: 'CEFR darajasi',
        startup: 'SafiqX',
        startupSub: 'Startap rejasi',
      },
      location: 'O\'zbekiston',
      tradingStatus: 'Trading · Faol',
      scroll: 'Pastga',
    },
    stats: {
      tradingXP: 'Trading tajribasi',
      tradingSub: 'Smart Money Konsepsiyalari',
      tradingDetail: 'Bank manipulyatsiyasi · Order bloklar · Multi-TF',
      projectsBuilt: 'Loyihalar',
      projectsSub: 'Faol tashabbuslar',
      projectsDetail: 'SafiqX · Trading tizimi · Shaxsiy brend',
      englishLevel: 'Ingliz tili',
      englishSub: 'CEFR sertifikatlangan',
      englishDetail: 'Universitetga kirish uchun IELTS 7+ maqsad qilingan',
      activeFocus: 'Faol yo\'nalish',
    },
    about: {
      label: 'Haqimda',
      title: 'Niyat ortidagi hikoya',
      paragraphs: [
        'Men 17 yoshli shijoatli tadbirkorman, global va halol moliyaviy ekotizim yaratishga e\'tibor qaratganman. Mening yo\'lim moliya bozorlariga bo\'lgan kuchli qiziqishdan boshlanib, trading strategiyalarini, ayniqsa "smart money" va bank manipulyatsiyasi konsepsiyalarini o\'zlashtirishga qadar yetdi.',
        'Men an\'anaviy yo\'ldan bormayapman. Boshqalar nazariyani o\'rganayotgan bir paytda, men real ko\'nikmalarga — trading, startaplar va global miqyosda kengaya oladigan tizimlar yaratishga e\'tibor qaratyapman. Men ko\'pchilik uyg\'onishidan oldin bozorlarni o\'rganaman va o\'qishdan keyin quraman.',
        'Mening maqsadim — brokerlik, aktivlarni boshqarish va sun\'iy intellektga asoslangan tahlillarni yagona kuchli platformaga birlashtirgan kompaniya qurish — odamlarning pul bilan munosabatini o\'zgartirish. Faqat foyda uchun emas, balki imkoniyatlar yaratish uchun.',
      ],
      quote: '"Men kelajakka tayyorgarlik ko\'rayotganim yo\'q — men uni qurayapman."',
      visionTitle: 'Niyat',
      visionText: "Dunyoning yetakchi moliyaviy institutlari bilan raqobatlasha oladigan global halol brokerlik va investitsiya ekotizimini qurish.",
      missionTitle: 'Missiya',
      missionText: 'Insonlarni chegarasiz, axloqiy, kuchli va aqlli moliyaviy vositalar bilan ta\'minlash.',
      mindsetTitle: 'Fikrlash tarzi',
      mindsetText: 'Intizom. Strategiya. Uzoq muddatli ustunlik. Har bir qaror hisoblangan, har bir qadam o\'ylangan.',
    },
    skills: {
      label: 'Mahorat',
      title: 'Ko\'nikmalar va tajriba',
      subtitle: 'Tafsilotlarni ko\'rish uchun kartaga bosing. Har bir ko\'nikma kelajakka qilingan ongli sarmoyadir.',
      tapToExplore: 'Tafsilotlarni ko\'rish uchun kartaga bosing ↑',
      activeFocus: 'Faol e\'tibor',
      categories: {
        business: 'Biznes va yetakchilik',
        trading: 'Trading va moliya',
        tech: 'Texnologiya va AI',
        comm: 'Muloqot',
      },
      descriptions: {
        business: 'Kengayuvchi tizimlar qurish. Har bir startap niyatdan boshlanadi — men niyatni amalga oshirish strategiyasiga aylantiraman.',
        trading: 'Institutsional darajadagi bozor tahlili. Men banklar narxni qanday harakatlantirishini o\'rganaman va aniqlik bilan bozorga kiraman.',
        tech: 'AIdan raqobatbardosh qurol sifatida foydalanish. Har qanday jamoadan tezroq harakat qilish uchun aqlli ish jarayonlarini yaratish.',
        comm: 'Til — bu imkoniyat. Men professional aniqlik va asoschi ishonchi bilan muloqot qilaman.',
      },
      details: {
        'Startup Building': 'G\'oyadan MVPgacha — loyihalarni investitsiya jalb qila oladigan darajaga keltirish.',
        'Strategic Thinking': 'Ko\'p bosqichli rejalashtirish: qisqa muddatli ijro + uzoq muddatli pozitsiya.',
        'Vision Planning': 'Ambitsiyali kompaniyalar uchun aniq maqsadlar va KPIlarni belgilash.',
        'Systems Design': 'Biznes, mahsulot va jarayonlarning o\'zaro qanday bog\'lanishini tushunish.',
        'Smart Money Concepts (SMC)': 'Institutsional order oqimi, premium/chegirma zonalari va FVGlarni kuzatish.',
        'Liquidity & Order Blocks': 'Banklar qaerda stop-ovlarni o\'rnatishini va pozitsiyalarni yig\'ishini aniqlash.',
        'Market Structure (BOS, CHoCH)': 'Trendni tasdiqlash uchun struktura buzilishi va xarakter o\'zgarishini o\'qish.',
        'Multi-timeframe Analysis': 'D1 hikoyasi → H4 tasdig\'i → M15 aniq kirish modeli.',
        'Bank Manipulation Strategy': 'Yirik ishtirokchilar likvidlikni qanday yaratishini tushunishga asoslangan shaxsiy ustunlik.',
        'Prompt Engineering': 'AI modellaridan maksimal foyda olish uchun aniq ko\'rsatmalar yaratish.',
        'AI-powered Workflows': 'Tahlil va kontent yaratish jarayonlarini avtomatlashtirish.',
        'Fullstack Understanding': 'Frontend, backend, ma\'lumotlar bazasi — barcha qatlamlarning bog\'lanishini tushunish.',
        'Frontend / Backend / DB': 'Startaplar qurish uchun zamonaviy veb-arxitektura bo\'yicha amaliy bilim.',
        'English — CEFR B2': 'Xalqaro universitetlarga kirish uchun faol ravishda IELTS 7+ ga tayyorgarlik.',
        'Professional Writing': 'Biznes muloqot, investorlar uchun briflar va strategik hujjatlar.',
        'Presentation Skills': 'G\'oyalarni aniqlik, ishonch va vizual hikoyalar orqali taqdim etish.',
        'Strategic Storytelling': 'Investorlar va hamkorlarni jalb qiladigan hikoyalar shakllantirish.',
      }
    },
    projects: {
      label: 'Loyihalar',
      title: 'Men nima quryapman',
      subtitle: 'Real rivojlanayotgan loyihalar — maktab topshiriqlari emas.',
      status: {
        dev: 'Rivojlanishda',
        research: 'Tahlil jarayonida',
        active: 'Faol',
      },
      safiqx: {
        tag: 'Startap konsepsiyasi',
        title: 'SafiqX',
        sub: 'Brokerlik va investitsiya kompaniyasi',
        desc: 'Trading, ilg\'or tahlillar (TradingView kabi) va AI tushunchalarini birlashtirgan yangi avlod halol brokerlik platformasi. BlackRock darajasidagi infratuzilmadan ilhomlangan.',
        h1: 'Trading ijro etish mexanizmi',
        h2: 'AI asosidagi bozor tahlillari',
        h3: 'Aktivlarni boshqarish tizimi',
        h4: 'Halol standartlarga mos tuzilma',
      },
      trading: {
        tag: 'Shaxsiy strategiya',
        title: 'Trading tizimi',
        sub: 'Bank manipulyatsiyasi strategiyasi',
        desc: 'Smart Money Konsepsiyalariga asoslangan shaxsiy strategiya — bank orderlari, likvidlik zonalari va struktura o\'zgarishlarini aniqlash.',
        h1: 'Smart Money Konsepsiyalari (SMC)',
        h2: 'Multi-taymfreym modeli (D1→M15)',
        h3: 'Likvidlikni aniqlash',
        h4: 'Risk nazorat qilingan struktura',
      },
      identity: {
        tag: 'Shaxsiy brend',
        title: 'Raqamli identifikatsiya',
        sub: 'Portfolion va shaxsiy brend tizimi',
        desc: 'Investorlar va hamkorlarni jalb qilish uchun mo\'ljallangan yuqori darajadagi raqamli identifikatsiya. Har bir nuqta niyat va intilishni ko\'rsatadi.',
        h1: 'Investor darajasidagi taqdimot',
        h2: 'Universitetlar uchun maqsadli portfolio',
        h3: 'Strategik shaxsiy hikoya',
        h4: 'Global ko\'rinish tizimi',
      }
    },
    vision: {
      label: 'Kelajakdagi kompaniya',
      title: 'SafiqX — Reja',
      subtitle: 'Dunyoning yetakchi moliyaviy institutlari bilan raqobatlasha oladigan yangi avlod halol brokerlik va investitsiya platformasi.',
      quote: '"SafiqX shunchaki fintex kompaniyasi emas. Bu — har bir musulmon va axloqiy investorga jahon darajasidagi moliyaviy infratuzilmadan foydalanish imkoniyatini beradigan harakatdir."',
      mission: 'SafiqX Missiyasi',
      goal: 'Maqsad: Axloqiy moliya sohasida global yetakchi',
      pillars: {
        p1: 'Trading ijrosi',
        p1d: 'Butun dunyo bo\'ylab chakana va professional treyderlar uchun institutsional darajadagi tizim.',
        p2: 'Ilg\'or tahlillar',
        p2d: 'Real vaqt rejimida bozor strukturasi tahlili va TradingView darajasidagi grafiklar.',
        p3: 'AI-tahlillar',
        p3d: 'Yuqori ehtimollikdagi vaziyatlarni va bozor namunalarini aniqlaydigan o\'rganish modellari.',
        p4: 'Aktivlarni boshqarish',
        p4d: 'Tizimli portfel boshqaruvi, BlackRock tajribasidan ilhomlangan holda.',
        p5: 'Halol muvofiqlik',
        p5d: '1,8 milliard musulmonlar uchun axloqiy sarmoya kiritishni ta\'minlaydigan to\'liq Shariatga mos tuzilma.',
      }
    },
    goals: {
      label: 'Yo\'l xaritasi',
      title: 'Maqsadlar va marralar',
      subtitle: 'Global moliyaviy imperiyani qurishga bo\'lgan bosqichma-bosqich yondashuv — bugundan boshlab.',
      phases: {
        p1: 'I-Bosqich',
        p1t: '2026 — Qisqa muddatli',
        p2: 'II-Bosqich',
        p2t: '2027–2028 — O\'rta muddatli',
        p3: 'III-Bosqich',
        p3t: '5–10 Yil — Uzoq muddatli',
      },
      items: {
        ielts: 'IELTS 7+ darajasiga erishish',
        portfolio: 'Kuchli universitet portfolioni yaratish',
        mvp: 'SafiqX startap MVPsini ishlab chiqish',
        ai: 'Prompt engineering va AI ko\'nikmalarini oshirish',
        trading: 'Trading natijalarini hujjatlashtirish',
        uni: 'Top xalqaro universitetga kirish',
        beta: 'SafiqX beta platformasini ishga tushirish',
        capital: 'Kuchli trading kapitalini yig\'ish',
        team: 'Maslahat va asoschilar jamoasini shakllantirish',
        investor: 'Dastlabki investorlar qiziqishini ta\'minlash',
        ceo: 'Global fintex kompaniyasi CEOsi bo\'lish',
        ecosystem: 'Ko\'p milliardli halol investitsiya ekotizimini qurish',
        global: 'SafiqXni global bozorlarga olib chiqish',
        compete: 'Yetakchi moliyaviy institutlar bilan raqobatlashish',
        empower: 'Millionlab insonlarga axloqiy moliya orqali imkoniyat berish',
      }
    },
    achievements: {
      label: 'Yutuqlar',
      title: 'Nimalarga erishdim',
      subtitle: '17 yoshdagi real yutuqlar — kattaroq narsaning asosi.',
      more: 'Yo\'l davomida ko\'proq yutuqlar qo\'shilib boradi...',
      items: {
        english: 'CEFR B2 Ingliz tili',
        englishSub: 'Til bilish mahorati',
        englishDesc: 'Ingliz tilida B2 darajasiga erishildi, xalqaro universitetga kirish uchun IELTS 7+ ustida ishlanmoqda.',
        trader: 'Faol SMC Treyder',
        traderSub: 'Trading mahorati',
        traderDesc: 'Smart Money Konsepsiyalarini o\'zlashtirish — bank manipulyatsiyasi va bozor strukturasi bo\'yicha chuqur bilim.',
        safiqx: 'SafiqX konsepsiyasi asoschisi',
        safiqxSub: 'Startapni rivojlantirish',
        safiqxDesc: 'Halol fintex brokerlik platformasi uchun to\'liq konsepsiyasi va infratuzilma rejasi yaratildi.',
        ai: 'AI va Prompt Engineering',
        aiSub: 'Texnik ko\'nikmalar',
        aiDesc: 'Biznesda AI vositalari va ish jarayonlarini avtomatlashtirish bo\'yicha mustaqil o\'rganilgan bilimlar.',
      }
    },
    contact: {
      label: 'Aloqa',
      title: 'Bog\'lanish',
      subtitle: 'Xohlagan kanal orqali bog\'laning — yoki pastda xabar qoldiring, men sizga javob beraman.',
      email: 'Email',
      telegram: 'Telegram',
      linkedin: 'LinkedIn',
      tapTo: 'Bosing:',
      open: 'Ochish',
      sendMsg: 'Xabar yuborish',
      form: {
        name: 'Ism',
        email: 'Email',
        subject: 'Mavzu',
        message: 'Xabar',
        namePlaceholder: 'Ismingiz',
        emailPlaceholder: 'sizning@email.com',
        subjectPlaceholder: 'Bu nima haqida?',
        messagePlaceholder: 'G\'oya yoki savolingizni yozing...',
        send: 'Xabarni yuborish',
        sending: 'Yuborilmoqda...',
        success: 'Xabar yuborildi!',
        successSub: 'Rahmat! Tez orada siz bilan bog\'lanaman.',
        sendAnother: 'Yana yuborish',
        error: 'Xatolik yuz berdi. To\'g\'ridan-to\'g\'ri email orqali yozib ko\'ring.',
        required: 'Iltimos, barcha majburiy maydonlarni to\'ldiring.',
      },
      quote: '"Men kelajakka tayyorgarlik ko\'rayotganim yo\'q — men uni qurayapman."',
      response: 'Odatda 24 soat ichida javob beradi',
      responseSub: 'Barcha xabarlar saqlanadi · Telegram orqali tezroq javob olishingiz mumkin',
      emailMe: 'To\'g\'ridan-to\'g\'ri email yozish',
      msgTelegram: 'Telegramda yozish',
    },
    footer: {
      sub: 'Kelajakdagi CEO · Fintex Asoschisi · O\'zbekiston · 2026',
      built: 'Niyat bilan qurilgan.',
    }
  },
  ru: {
    nav: {
      about: 'О себе',
      skills: 'Навыки',
      projects: 'Проекты',
      vision: 'Видение',
      goals: 'Цели',
      contact: 'Контакт',
      connect: 'Связаться',
    },
    hero: {
      status: 'Открыт к возможностям',
      shohijahon: 'Шохижахон',
      turdaliyev: 'Турдалиев',
      titles: ['Будущий CEO', 'Основатель Финтеха', 'Трейдинг Стратег'],
      tagline: '"Создание халяльной финансовой экосистемы и переосмысление будущего трейдинга через видение, дисциплину и инновации."',
      viewJourney: 'Посмотреть мой путь',
      contactMe: 'Связаться со мной',
      stats: {
        age: '17 лет',
        ageSub: 'Возраст основателя',
        english: 'B2 Английский',
        englishSub: 'Уровень CEFR',
        startup: 'SafiqX',
        startupSub: 'Видение стартапа',
      },
      location: 'Узбекистан',
      tradingStatus: 'Трейдинг · Активен',
      scroll: 'Листать',
    },
    stats: {
      tradingXP: 'Опыт трейдинга',
      tradingSub: 'Smart Money Concepts',
      tradingDetail: 'Банковские манипуляции · Order Blocks · Multi-TF',
      projectsBuilt: 'Создано проектов',
      projectsSub: 'Активные венчуры',
      projectsDetail: 'SafiqX · Трейдинг система · Личный бренд',
      englishLevel: 'Уровень английского',
      englishSub: 'Сертифицирован CEFR',
      englishDetail: 'Цель IELTS 7+ для поступления в университет',
      activeFocus: 'Активный фокус',
    },
    about: {
      label: 'О себе',
      title: 'История за видением',
      paragraphs: [
        'Я 17-летний амбициозный предприниматель, сосредоточенный на создании глобальной халяльной финансовой экосистемы. Мой путь начался с глубокого любопытства к финансовым рынкам и перерос в освоение стратегий трейдинга, в частности концепций "умных денег" и банковских манипуляций.',
        'Я не следую традиционным путем. Пока другие изучают теорию, я фокусируюсь на реальных навыках — трейдинге, стартапах и создании систем, которые могут масштабироваться глобально. Я изучаю рынки раньше, чем большинство людей просыпаются, и строю после занятий.',
        'Моя миссия — создать компанию, которая объединит брокерские услуги, управление активами и анализ на основе ИИ в одну мощную платформу, меняя то, как люди взаимодействуют с деньгами. Не только ради прибыли, но и для расширения возможностей.',
      ],
      quote: '"Я не готовлюсь к будущему — я его строю."',
      visionTitle: 'Видение',
      visionText: "Создать глобальную халяльную брокерскую и инвестиционную экосистему, конкурирующую с ведущими мировыми финансовыми институтами.",
      missionTitle: 'Миссия',
      missionText: 'Обеспечить людей этичными, мощными и интеллектуальными финансовыми инструментами без границ.',
      mindsetTitle: 'Мышление',
      mindsetText: 'Дисциплина. Стратегия. Долгосрочное доминирование. Каждое решение просчитано, каждый шаг обдуман.',
    },
    skills: {
      label: 'Экспертиза',
      title: 'Навыки и мастерство',
      subtitle: 'Нажмите на карточку, чтобы узнать больше. Каждый навык — это осознанная инвестиция в будущее.',
      tapToExplore: 'Нажмите на любую карточку для подробностей ↑',
      activeFocus: 'Активный фокус',
      categories: {
        business: 'Бизнес и лидерство',
        trading: 'Трейдинг и финансы',
        tech: 'Технологии и ИИ',
        comm: 'Коммуникации',
      },
      descriptions: {
        business: 'Создание масштабируемых систем. Каждый стартап начинается с видения — я перевожу видение в стратегию исполнения.',
        trading: 'Анализ рынка институционального уровня. Я изучаю, как банки двигают цену, и вхожу с высокой точностью.',
        tech: 'Использование ИИ как конкурентного преимущества. Создание интеллектуальных рабочих процессов.',
        comm: 'Язык — это рычаг. Я общаюсь с профессиональной точностью и убежденностью основателя.',
      },
      details: {
        'Startup Building': 'От концепции до MVP — структурирование идей в масштабируемые венчуры.',
        'Strategic Thinking': 'Многоуровневое планирование: исполнение + позиционирование на рынке.',
        'Vision Planning': 'Установка четких целей и KPI для амбициозных компаний.',
        'Systems Design': 'Понимание того, как бизнес, продукты и процессы связаны воедино.',
        'Smart Money Concepts (SMC)': 'Отслеживание институциональных ордеров, зон премиум/дискаунт и FVG.',
        'Liquidity & Order Blocks': 'Определение зон ликвидности и накопления позиций банками.',
        'Market Structure (BOS, CHoCH)': 'Чтение структуры рынка для подтверждения тренда.',
        'Multi-timeframe Analysis': 'Нарратив D1 → подтверждение H4 → точный вход M15.',
        'Bank Manipulation Strategy': 'Понимание того, как крупные игроки создают ликвидность.',
        'Prompt Engineering': 'Создание точных инструкций для ИИ-моделей.',
        'AI-powered Workflows': 'Автоматизация исследований, анализа и создания контента.',
        'Fullstack Understanding': 'Frontend, backend, базы данных — понимание всех связей.',
        'Frontend / Backend / DB': 'Практические знания веб-архитектуры для создания стартапов.',
        'English — CEFR B2': 'Активная подготовка к IELTS 7+ для поступления в топ-университеты.',
        'Professional Writing': 'Бизнес-коммуникации, брифы для инвесторов и документация.',
        'Presentation Skills': 'Питчинг идей с ясностью, уверенностью и визуальным сторителлингом.',
        'Strategic Storytelling': 'Формирование историй, привлекающих инвесторов и партнеров.',
      }
    },
    projects: {
      label: 'Проекты',
      title: 'Что я строю',
      subtitle: 'Реальные венчуры в разработке — не школьные проекты.',
      status: {
        dev: 'В разработке',
        research: 'Исследование',
        active: 'Активен',
      },
      safiqx: {
        tag: 'Концепция стартапа',
        title: 'SafiqX',
        sub: 'Брокерская и инвестиционная компания',
        desc: 'Халяльная брокерская платформа нового поколения, объединяющая исполнение сделок, аналитику и ИИ. Вдохновлено инфраструктурой уровня BlackRock.',
        h1: 'Движок исполнения сделок',
        h2: 'Рыночные идеи на базе ИИ',
        h3: 'Система управления активами',
        h4: 'Халяльная структура',
      },
      trading: {
        tag: 'Личная стратегия',
        title: 'Трейдинг система',
        sub: 'Стратегия банковских манипуляций',
        desc: 'Личная торговая стратегия, основанная на Smart Money Concepts — идентификация ордеров банков и зон ликвидности.',
        h1: 'Smart Money Concepts (SMC)',
        h2: 'Мульти-таймфрейм модель (D1→M15)',
        h3: 'Идентификация ликвидности',
        h4: 'Структура с управлением рисками',
      },
      identity: {
        tag: 'Личный бренд',
        title: 'Цифровая личность',
        sub: 'Портфолио и личный бренд',
        desc: 'Создание высококонверсионной цифровой личности для привлечения инвесторов и партнеров. Каждая точка контакта передает амбиции.',
        h1: 'Презентация уровня инвестора',
        h2: 'Портфолио для университетов',
        h3: 'Стратегический сторителлинг',
        h4: 'Система глобальной видимости',
      }
    },
    vision: {
      label: 'Будущая компания',
      title: 'SafiqX — Видение',
      subtitle: 'Халяльная брокерская и инвестиционная платформа нового поколения, призванная конкурировать с ведущими финансовыми институтами мира.',
      quote: '"SafiqX — это не просто финтех-компания. Это движение — дать каждому мусульманину и этичному инвестору доступ к финансовой инфраструктуре мирового уровня."',
      mission: 'Миссия SafiqX',
      goal: 'Цель: Глобальный лидер в этичных финансах',
      pillars: {
        p1: 'Исполнение сделок',
        p1d: 'Движок исполнения институционального уровня для розничных и профессиональных трейдеров.',
        p2: 'Продвинутая аналитика',
        p2d: 'Графики уровня TradingView и анализ структуры рынка в реальном времени.',
        p3: 'Идеи на базе ИИ',
        p3d: 'Модели машинного обучения, определяющие высоковероятные сетапы и паттерны.',
        p4: 'Управление активами',
        p4d: 'Систематическое управление портфелем, вдохновленное BlackRock.',
        p5: 'Халяльное соответствие',
        p5d: 'Полностью соответствующая Шариату структура, обеспечивающая этичное инвестирование.',
      }
    },
    goals: {
      label: 'Дорожная карта',
      title: 'Цели и этапы',
      subtitle: 'Структурированный, поэтапный подход к построению глобальной финансовой империи — начиная сегодня.',
      phases: {
        p1: 'Фаза I',
        p1t: '2026 — Краткосрочная',
        p2: 'Фаза II',
        p2t: '2027–2028 — Среднесрочная',
        p3: 'Фаза III',
        p3t: '5–10 лет — Долгосрочная',
      },
      items: {
        ielts: 'Получить IELTS 7+',
        portfolio: 'Создать сильное университетское портфолио',
        mvp: 'Разработать MVP стартапа (SafiqX)',
        ai: 'Улучшить навыки Prompt Engineering и ИИ',
        trading: 'Установить рекорд торговых результатов',
        uni: 'Поступить в топ-международный университет',
        beta: 'Запустить бета-платформу SafiqX',
        capital: 'Создать сильную базу торгового капитала',
        team: 'Сформировать консультативный совет и команду',
        investor: 'Обеспечить интерес первых инвесторов',
        ceo: 'Стать CEO глобальной финтех-компании',
        ecosystem: 'Построить многомиллиардную халяльную экосистему',
        global: 'Вывести SafiqX на глобальные рынки',
        compete: 'Конкурировать с финансовыми институтами высшего уровня',
        empower: 'Дать возможности миллионам через этичные финансы',
      }
    },
    achievements: {
      label: 'Достижения',
      title: 'Чего я добился',
      subtitle: 'Реальные достижения в 17 лет — фундамент для чего-то гораздо большего.',
      more: 'Больше достижений добавляется по мере продолжения пути...',
      items: {
        english: 'Английский CEFR B2',
        englishSub: 'Знание языка',
        englishDesc: 'Достигнут уровень B2, идет активная работа над IELTS 7+ для поступления в топ-университеты.',
        trader: 'Активный SMC Трейдер',
        traderSub: 'Мастерство трейдинга',
        traderDesc: 'Освоение Smart Money Concepts — глубокое понимание манипуляций и структуры рынка.',
        safiqx: 'Основана концепция SafiqX',
        safiqxSub: 'Разработка стартапа',
        safiqxDesc: 'Создана полная концепция и план инфраструктуры для халяльной брокерской платформы.',
        ai: 'ИИ и Prompt Engineering',
        aiSub: 'Тех навыки',
        aiDesc: 'Самостоятельное освоение инструментов ИИ и автоматизации рабочих процессов.',
      }
    },
    contact: {
      label: 'Контакт',
      title: 'Свяжемся',
      subtitle: 'Свяжитесь со мной по любому каналу — или отправьте сообщение ниже, и я отвечу.',
      email: 'Email',
      telegram: 'Telegram',
      linkedin: 'LinkedIn',
      tapTo: 'Нажмите:',
      open: 'Открыть',
      sendMsg: 'Отправить сообщение',
      form: {
        name: 'Имя',
        email: 'Email',
        subject: 'Тема',
        message: 'Сообщение',
        namePlaceholder: 'Ваше имя',
        emailPlaceholder: 'vash@email.com',
        subjectPlaceholder: 'О чем речь?',
        messagePlaceholder: 'Расскажите мне о вашей идее или вопросе...',
        send: 'Отправить сообщение',
        sending: 'Отправка...',
        success: 'Сообщение отправлено!',
        successSub: 'Спасибо! Я свяжусь с вами как можно скорее.',
        sendAnother: 'Отправить еще',
        error: 'Что-то пошло не так. Попробуйте написать на email.',
        required: 'Пожалуйста, заполните все обязательные поля.',
      },
      quote: '"Я не готовлюсь к будущему — я его строю."',
      response: 'Обычно отвечает в течение 24 часов',
      responseSub: 'Все сообщения сохранены · В Telegram отвечаю быстрее',
      emailMe: 'Написать на email напрямую',
      msgTelegram: 'Написать в Telegram',
    },
    footer: {
      sub: 'Будущий CEO · Основатель Финтеха · Узбекистан · 2026',
      built: 'Создано с видением.',
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (path: string) => {
    return path.split('.').reduce((obj, key) => obj?.[key], translations[language] as any) || path;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
